# Generated by Django 2.0.8 on 2018-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_auto_20181123_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signform',
            name='sign_request',
        ),
        migrations.AddField(
            model_name='signrequest',
            name='forms',
            field=models.ManyToManyField(to='esign.SignForm'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
