# Generated by Django 2.0.8 on 2018-11-23 11:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_auto_20181123_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrequest',
            name='agent',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
