# Generated by Django 2.0.8 on 2018-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0004_auto_20181123_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(to='esign.DocumentFile'),
        ),
    ]
